import streamlit as st


def render_home():
    st.markdown("""
    <div class="hero-section">
        <h1 class="hero-title">🧠 Explainable Resume Screener</h1>
        <p class="hero-subtitle">
            Go beyond keyword matching. Understand <em>why</em> a resume fits a job —
            powered by semantic embeddings, SHAP explanations, and LLM-generated insights.
        </p>
    </div>
    """, unsafe_allow_html=True)

    col1, col2, col3, col4 = st.columns(4)

    with col1:
        st.markdown("""
        <div class="feature-card">
            <div class="feature-icon">🎯</div>
            <h3>Semantic Matching</h3>
            <p>Transformer embeddings capture meaning, not just keywords. Compare skills contextually.</p>
        </div>
        """, unsafe_allow_html=True)

    with col2:
        st.markdown("""
        <div class="feature-card">
            <div class="feature-icon">🔍</div>
            <h3>SHAP Explanations</h3>
            <p>Understand which skills and experiences drove the match score using SHAP values.</p>
        </div>
        """, unsafe_allow_html=True)

    with col3:
        st.markdown("""
        <div class="feature-card">
            <div class="feature-icon">🔄</div>
            <h3>Counterfactual Analysis</h3>
            <p>See what changes would increase your match score — actionable "what-if" scenarios.</p>
        </div>
        """, unsafe_allow_html=True)

    with col4:
        st.markdown("""
        <div class="feature-card">
            <div class="feature-icon">💬</div>
            <h3>LLM Insights</h3>
            <p>Plain-English explanations generated by an LLM — no data science jargon.</p>
        </div>
        """, unsafe_allow_html=True)

    st.markdown("---")

    col_a, col_b = st.columns([2, 1])
    with col_a:
        st.markdown("""
        ### How it works
        1. **Upload or paste** your resume and the job description
        2. **Run analysis** — our model computes semantic similarity scores for each skill/section
        3. **View explanations** — SHAP values reveal what's helping or hurting your score
        4. **Counterfactual suggestions** — discover the smallest changes to boost your match
        5. **LLM summary** — get a friendly, grounded explanation of your results
        """)
    with col_b:
        st.info("💡 **Tip:** This system explains decisions — perfect for fair, transparent hiring workflows.")

    st.markdown("---")
    if st.button("🚀 Get Started — Analyze My Resume", type="primary", use_container_width=True):
        st.session_state.page = "analyzer"
        st.rerun()
